version: '3.9'

services:
  service:
    container_name: salesforce_api
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VERSION: ${VERSION}
        COMMIT_SHA: ${COMMIT_SHA}
    volumes:
      - ./src:/tmp/src
    ports:
      - "8080:8080"
